---
name:

logging:
  level: INFO

dir:

network:
  type: dynamic
  cloud_properties: {}

env:
  bosh:
    password:

resources:
  persistent_disk: 4096
  cloud_properties:
    instance_type: n1.standard.1
    availability_zone:

cloud:
  plugin: google
  properties:
    google:
      client_email:
      project:
      client_key_path:
      storage_access:
      storage_secret:
      private_key_path: '~/.ssh/id_rsa'
      public_key_path:  '~/.ssh/id_rsa.pub'

      endpoint_type: publicURL
      ssh_user: vcap
    registry:
      endpoint: http://admin:admin@localhost:25889
      user: admin
      password: admin
    agent:
      ntp: []
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      mbus:

apply_spec:
  properties: {}
  agent:
    blobstore: {}
    nats: {}
